//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetHoseContainer : DbContext
    {
        public MetHoseContainer()
            : base("name=MetHoseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCorrugSheath> tCorrugSheathSet { get; set; }
        public virtual DbSet<tMaterial> tMaterialSet { get; set; }
        public virtual DbSet<tGlass> tGlassSet { get; set; }
        public virtual DbSet<tBraid> tBraidSet { get; set; }
        public virtual DbSet<tRing> tRingSet { get; set; }
        public virtual DbSet<tMetHose> tMetHoseSet { get; set; }
        public virtual DbSet<tSpecification> tSpecificationSet { get; set; }
        public virtual DbSet<tLength> tLengthSet { get; set; }
        public virtual DbSet<tAssemblySp> tAssemblySpSet { get; set; }
        public virtual DbSet<tDetailSp> tDetailSpSet { get; set; }
        public virtual DbSet<tAdapter> tAdapterSet { get; set; }
        public virtual DbSet<tBufer> tBuferSet { get; set; }
        public virtual DbSet<tAsDet> tAsDetSet { get; set; }
        public virtual DbSet<tAsSp> tAsSpSet { get; set; }
        public virtual DbSet<tDetSp> tDetSpSet { get; set; }
    }
}
