//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetHoseContainer : DbContext
    {
        public MetHoseContainer()
            : base("name=MetHoseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCorrugSheath> tCorrugSheathSet { get; set; }
        public virtual DbSet<tMaterial> tMaterialSet { get; set; }
        public virtual DbSet<tGlass> tGlassSet { get; set; }
        public virtual DbSet<tBraid> tBraidSet { get; set; }
        public virtual DbSet<tRing> tRingSet { get; set; }
        public virtual DbSet<tMetHose> tMetHoseSet { get; set; }
    }
}
