//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAdapter
    {
        public int ID { get; set; }
        public string NumbElement { get; set; }
        public int tDetailSpID { get; set; }
        public Nullable<int> tLengthID_length { get; set; }
        public Nullable<int> tBraidID_braid { get; set; }
        public Nullable<int> tRingID_ring { get; set; }
        public Nullable<int> tGlassID_glass { get; set; }
    
        public virtual tDetailSp tDetailSp { get; set; }
        public virtual tLength tLength { get; set; }
        public virtual tBraid tBraid { get; set; }
        public virtual tRing tRing { get; set; }
        public virtual tGlass tGlass { get; set; }
    }
}
