//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAssemblySp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tAssemblySp()
        {
            this.tAsDet = new HashSet<tAsDet>();
            this.tAsSp = new HashSet<tAsSp>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AssemblyRef { get; set; }
        public Nullable<int> PosAssembly { get; set; }
        public string NameAss { get; set; }
        public int QuantityAss { get; set; }
        public Nullable<int> Detail { get; set; }
        public Nullable<int> StandProdAss { get; set; }
        public Nullable<int> OtherProdAss { get; set; }
        public Nullable<int> Kits { get; set; }
        public string Description { get; set; }
        public Nullable<int> tBuferID { get; set; }
    
        public virtual tBufer tBufer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAsDet> tAsDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAsSp> tAsSp { get; set; }
    }
}
