//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBraid
    {
        public int ID { get; set; }
        public short DN { get; set; }
        public string TypeBr { get; set; }
        public double Dout { get; set; }
        public double Din { get; set; }
        public Nullable<short> NumbStrands { get; set; }
        public Nullable<short> NymbThreads { get; set; }
        public double DThreads { get; set; }
        public Nullable<double> AngleWeaving { get; set; }
        public string Executor { get; set; }
        public string Description { get; set; }
        public int tMaterialID { get; set; }
    
        public virtual tMaterial tMaterial { get; set; }
    }
}
