//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBraid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBraid()
        {
            this.tMetHose = new HashSet<tMetHose>();
        }
    
        public int ID { get; set; }
        public string DN { get; set; }
        public string Type { get; set; }
        public string Dout { get; set; }
        public string Din { get; set; }
        public string NumbStrands { get; set; }
        public string NymbThreads { get; set; }
        public string DThreads { get; set; }
        public string AngleWeaving { get; set; }
        public string Executor { get; set; }
        public string Description { get; set; }
        public int tMaterialID { get; set; }
    
        public virtual tMaterial tMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMetHose> tMetHose { get; set; }
    }
}
