//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBufer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tBufer()
        {
            this.tAssemblySp = new HashSet<tAssemblySp>();
        }
    
        public int ID { get; set; }
        public Nullable<short> D1 { get; set; }
        public Nullable<short> D2 { get; set; }
        public Nullable<short> D3 { get; set; }
        public Nullable<short> D4 { get; set; }
        public Nullable<short> D5 { get; set; }
        public Nullable<short> D6 { get; set; }
        public Nullable<short> D7 { get; set; }
        public Nullable<short> D8 { get; set; }
        public Nullable<short> D9 { get; set; }
        public string exp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAssemblySp> tAssemblySp { get; set; }
    }
}
