//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tGlass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tGlass()
        {
            this.tMetHose = new HashSet<tMetHose>();
        }
    
        public int ID { get; set; }
        public short DN { get; set; }
        public string Name { get; set; }
        public string UntypicalName { get; set; }
        public Nullable<bool> UntypicalCheck { get; set; }
        public double Dout { get; set; }
        public double Th { get; set; }
        public double Ls { get; set; }
        public string Executor { get; set; }
        public string Description { get; set; }
        public int tMaterialID { get; set; }
    
        public virtual tMaterial tMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMetHose> tMetHose { get; set; }
    }
}
