//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tLength
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tLength()
        {
            this.tSpecification_tCorrugSheath = new HashSet<tSpecification_tCorrugSheath>();
        }
    
        public int ID_length { get; set; }
        public double LN { get; set; }
        public int tCorrugSheathID_corrugsheath { get; set; }
    
        public virtual tCorrugSheath tCorrugSheath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSpecification_tCorrugSheath> tSpecification_tCorrugSheath { get; set; }
    }
}
