//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMetHose
    {
        public int ID { get; set; }
        public int tCorrugSheathID { get; set; }
        public Nullable<int> tBraidID { get; set; }
        public Nullable<int> tGlassID { get; set; }
        public Nullable<int> tCorrugSheathID1 { get; set; }
    
        public virtual tBraid tBraid { get; set; }
        public virtual tGlass tGlass { get; set; }
        public virtual tRing tRing { get; set; }
        public virtual tCorrugSheath tCorrugSheath { get; set; }
    }
}
