//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMetHose
    {
        public int ID { get; set; }
        public short DN { get; set; }
        public double PN { get; set; }
        public string NamePrimary { get; set; }
        public string NameSecondary { get; set; }
        public Nullable<double> PHydTest { get; set; }
        public Nullable<double> PPneumTest { get; set; }
        public string Description { get; set; }
        public string Executor { get; set; }
        public Nullable<int> tCorrugSheathID { get; set; }
        public Nullable<int> tBraidID { get; set; }
    
        public virtual tCorrugSheath tCorrugSheath { get; set; }
        public virtual tBraid tBraid { get; set; }
        public virtual tGlass tGlass { get; set; }
        public virtual tRing tRing { get; set; }
    }
}
