//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMetHose
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMetHose()
        {
            this.tCorrugSheath = new HashSet<tCorrugSheath>();
            this.tBraid = new HashSet<tBraid>();
            this.tGlass = new HashSet<tGlass>();
            this.tRing = new HashSet<tRing>();
        }
    
        public int ID { get; set; }
        public short DN { get; set; }
        public double PN { get; set; }
        public string NamePrimary { get; set; }
        public string NameSecondary { get; set; }
        public Nullable<double> PHydTest { get; set; }
        public Nullable<double> PPneumTest { get; set; }
        public string Description { get; set; }
        public string Executor { get; set; }
        public Nullable<int> tCorrugSheathID { get; set; }
        public Nullable<int> tBraidID { get; set; }
        public Nullable<int> tGlassID { get; set; }
        public Nullable<int> tRingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tCorrugSheath> tCorrugSheath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tBraid> tBraid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tGlass> tGlass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tRing> tRing { get; set; }
    }
}
