//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRing
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public short DN { get; set; }
        public double PN { get; set; }
        public double Dout { get; set; }
        public double Th { get; set; }
        public double LN { get; set; }
        public string WeldingSide { get; set; }
        public Nullable<double> ChamExtR { get; set; }
        public Nullable<double> ChamExtL { get; set; }
        public Nullable<double> ChamIntR { get; set; }
        public Nullable<double> ChamIntL { get; set; }
        public Nullable<double> AngleExtR { get; set; }
        public Nullable<double> AngleExtL { get; set; }
        public Nullable<double> AngleIntR { get; set; }
        public Nullable<double> AngleIntL { get; set; }
        public Nullable<double> BoringExtR { get; set; }
        public Nullable<double> BoringExtL { get; set; }
        public Nullable<double> BoringIntR { get; set; }
        public Nullable<double> BoringIntL { get; set; }
        public Nullable<double> AngleCoupExtR { get; set; }
        public Nullable<double> AngleCoupExtL { get; set; }
        public Nullable<double> AngleCoupIntR { get; set; }
        public Nullable<double> AngleCoupIntL { get; set; }
        public string Description { get; set; }
        public string Executor { get; set; }
        public int tMaterialID { get; set; }
    
        public virtual tMaterial tMaterial { get; set; }
    }
}
