//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSpecification_Ring
    {
        public int ID_SpecRing { get; set; }
        public int ID_specification { get; set; }
        public int ID_ring { get; set; }
        public int tSpecificationID_specification { get; set; }
        public int tRingID_ring { get; set; }
    
        public virtual tSpecification tSpecification { get; set; }
        public virtual tRing tRing { get; set; }
    }
}
