//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSpecification()
        {
            this.tSpecification_tCorrugSheath = new HashSet<tSpecification_tCorrugSheath>();
            this.tSpecification_Braid = new HashSet<tSpecification_Braid>();
            this.tSpecification_Glass = new HashSet<tSpecification_Glass>();
            this.tSpecification_Ring = new HashSet<tSpecification_Ring>();
        }
    
        public int ID_specification { get; set; }
        public int id_item { get; set; }
        public string Name { get; set; }
        public short Position { get; set; }
        public string Quantity { get; set; }
    
        public virtual tMetHose tMetHose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSpecification_tCorrugSheath> tSpecification_tCorrugSheath { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSpecification_Braid> tSpecification_Braid { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSpecification_Glass> tSpecification_Glass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tSpecification_Ring> tSpecification_Ring { get; set; }
    }
}
