//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSpecification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tSpecification()
        {
            this.tAsSp = new HashSet<tAsSp>();
            this.tDetSp = new HashSet<tDetSp>();
        }
    
        public int ID_Specification { get; set; }
        public Nullable<int> AssemblyG { get; set; }
        public Nullable<int> DetailG { get; set; }
        public Nullable<int> StandartProductsG { get; set; }
        public Nullable<int> OtherProductsG { get; set; }
        public Nullable<int> KitsG { get; set; }
        public System.DateTime dateT { get; set; }
        public byte[] Drawing { get; set; }
        public string Description { get; set; }
        public string Executor { get; set; }
    
        public virtual tMetHose tMetHose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAsSp> tAsSp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetSp> tDetSp { get; set; }
    }
}
