//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSpecification_tCorrugSheath
    {
        public int ID_SpecCorSh { get; set; }
        public int ID_specification { get; set; }
        public int ID_corrugsheath { get; set; }
        public int tSpecificationID_specification { get; set; }
        public int tCorrugSheathID_corrugsheath { get; set; }
    
        public virtual tSpecification tSpecification { get; set; }
        public virtual tCorrugSheath tCorrugSheath { get; set; }
    }
}
